version: '3.8'
services:
  storage-seaweedfs:
    image: 'chrislusf/seaweedfs:latest'
    command: 'server -s3 -s3.port=8333'
    volumes:
      - 'seaweedfs-data:/data'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9333/cluster/status"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
    network_mode: service:lazytainer
    depends_on:
      - lazytainer
    labels:
      - "lazytainer.group=seaweedfs"

volumes:
  seaweedfs-data:
