version: '3.8'
services:
  monitoring-lgtm:
    image: grafana/otel-lgtm:latest
    volumes:
      - lgtm-data:/data
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    networks:
      - monitoring-network
      - database-network
      - queue-network
      - mail-network
    deploy:
      resources:
        limits:
          memory: 1G


networks:
  monitoring-network:
    driver: bridge

volumes:
  lgtm-data: