version: '3.8'
services:
  monitoring-lgtm:
    image: grafana/otel-lgtm:latest
    volumes:
      - lgtm-data:/data
    deploy:
      resources:
        limits:
          memory: 1G
    network_mode: service:lazytainer
    depends_on:
      - lazytainer
    labels:
      - "lazytainer.group=lgtm"

volumes:
  lgtm-data:
