version: '3.8'
services:
  mq-redpanda:
    image: 'redpandadata/redpanda:latest'
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9092
    environment:
      REDPANDA_AUTO_CREATE_TOPICS: "true"
      REDPANDA_DEFAULT_REPLICATION_FACTOR: 1
      REDPANDA_LOG_LEVEL: info
      REDPANDA_DEVELOPER_MODE: "true"
    ports:
      - "9092:9092"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - queue-network
    deploy:
      resources:
        limits:
          memory: 1G

  mq-rabbitmq:
    image: 'rabbitmq:alpine'
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq-data:/var/lib/rabbitmq'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - queue-network
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  queue-network:
    driver: bridge

volumes:
  redpanda-data:
  rabbitmq-data: 