version: '3.8'
services:
  mailing-mailpit:
    image: 'axllent/mailpit:latest'
    environment:
      MP_DATABASE: /data/mailpit.db
    volumes:
      - 'mailpit-data:/data'
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "--max-time", "5", "http://localhost:8025/readyz"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
    network_mode: service:lazytainer
    depends_on:
      - lazytainer
    labels:
      - "lazytainer.group=mailpit"

volumes:
  mailpit-data:
