version: '3.8'
services:
  mailing-mailhog:
    image: 'mailhog/mailhog'
    deploy:
      resources:
        limits:
          memory: 256M
    network_mode: service:lazytainer
    depends_on:
      - lazytainer
    labels:
      - "lazytainer.group=mailhog"
