apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    url: http://monitoring-mimir:9009/prometheus
    jsonData:
      httpMethod: GET

  - name: Loki
    type: loki
    access: proxy
    url: http://monitoring-loki:3100
    jsonData:
      maxLines: 1000

  - name: Tempo
    type: tempo
    access: proxy
    url: http://monitoring-tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: "prometheus"
